package verification

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/ThirdKeyAi/agentpin/go/pkg/credential"
	"github.com/ThirdKeyAi/agentpin/go/pkg/crypto"
	"github.com/ThirdKeyAi/agentpin/go/pkg/jwk"
	"github.com/ThirdKeyAi/agentpin/go/pkg/jwt"
	"github.com/ThirdKeyAi/agentpin/go/pkg/pinning"
	"github.com/ThirdKeyAi/agentpin/go/pkg/types"
)

// These tests use Rust-generated fixtures to prove the Go SDK's wire format
// is byte-compatible with the Rust SDK. The fixtures are generated by
// `agentpin keygen` (Rust CLI) and committed under testdata/. Regenerating
// them is a manual step documented in go/README.md.

const fixturesDir = "testdata"

func loadFixture(t *testing.T, name string) []byte {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(fixturesDir, name))
	if err != nil {
		t.Fatalf("read fixture %s: %v", name, err)
	}
	return data
}

// TestCrossLang_PEMtoJWK_MatchesRust loads a Rust-generated PEM public key,
// converts it to a JWK using the Go SDK, and asserts the result is equal to
// the JWK file generated by the Rust CLI. Wire format is a security
// guarantee: any drift here breaks cross-language interop.
func TestCrossLang_PEMtoJWK_MatchesRust(t *testing.T) {
	pubPEM := string(loadFixture(t, "example-2026-01.public.pem"))
	jwkData := loadFixture(t, "example-2026-01.public.jwk.json")

	var rustJWK types.JWK
	if err := json.Unmarshal(jwkData, &rustJWK); err != nil {
		t.Fatalf("parse rust JWK: %v", err)
	}

	goJWK, err := jwk.PEMToJWK(pubPEM, "example-2026-01")
	if err != nil {
		t.Fatalf("Go PEMToJWK: %v", err)
	}
	if goJWK.Kid != rustJWK.Kid {
		t.Fatalf("kid mismatch: Go=%s Rust=%s", goJWK.Kid, rustJWK.Kid)
	}
	if goJWK.Kty != rustJWK.Kty || goJWK.Crv != rustJWK.Crv {
		t.Fatalf("kty/crv mismatch")
	}
	if goJWK.X != rustJWK.X || goJWK.Y != rustJWK.Y {
		t.Fatalf("x/y coordinate mismatch:\nGo  : x=%s y=%s\nRust: x=%s y=%s",
			goJWK.X, goJWK.Y, rustJWK.X, rustJWK.Y)
	}
	if goJWK.Use != rustJWK.Use {
		t.Fatalf("use mismatch: Go=%s Rust=%s", goJWK.Use, rustJWK.Use)
	}
}

// TestCrossLang_JWKThumbprint_MatchesRustPort confirms the Go RFC 7638
// thumbprint matches what we'd compute on the Rust side using the same JWK.
// The expected hash is computed inline from the canonical JWK form so any
// regression in canonicalization is immediately visible.
func TestCrossLang_JWKThumbprint_MatchesRustPort(t *testing.T) {
	jwkData := loadFixture(t, "example-2026-01.public.jwk.json")
	var j types.JWK
	if err := json.Unmarshal(jwkData, &j); err != nil {
		t.Fatal(err)
	}
	tp := jwk.JWKThumbprint(&j)
	if len(tp) != 64 {
		t.Fatalf("thumbprint hex length %d, want 64", len(tp))
	}
	// Recompute the canonical input independently and SHA-256 it; this
	// asserts the canonical form matches RFC 7638 exactly.
	canonical := `{"crv":"P-256","kty":"EC","x":"` + j.X + `","y":"` + j.Y + `"}`
	if got := crypto.SHA256Hex([]byte(canonical)); got != tp {
		t.Fatalf("thumbprint mismatch: %s vs %s", tp, got)
	}
}

// TestCrossLang_DiscoveryDocument_RustSerialization_RoundTrip parses a
// Rust-generated discovery document and validates it loads correctly with
// the same field names. This catches any JSON tag drift.
func TestCrossLang_DiscoveryDocument_RustSerialization_RoundTrip(t *testing.T) {
	data := loadFixture(t, "discovery.json")
	var doc types.DiscoveryDocument
	if err := json.Unmarshal(data, &doc); err != nil {
		t.Fatalf("parse discovery: %v", err)
	}
	if doc.Entity != "example.com" {
		t.Fatalf("entity: %s", doc.Entity)
	}
	if doc.AgentpinVersion != "0.1" {
		t.Fatalf("agentpin_version: %s", doc.AgentpinVersion)
	}
	if doc.EntityType != types.EntityMaker {
		t.Fatalf("entity_type: %s", doc.EntityType)
	}
	if len(doc.PublicKeys) != 1 || doc.PublicKeys[0].Kid != "example-2026-01" {
		t.Fatalf("public_keys: %+v", doc.PublicKeys)
	}
	if len(doc.Agents) != 1 {
		t.Fatalf("agents: %+v", doc.Agents)
	}
	if doc.Agents[0].AgentID != "urn:agentpin:example.com:test-agent" {
		t.Fatalf("agent_id: %s", doc.Agents[0].AgentID)
	}
	if doc.Agents[0].Status != types.AgentActive {
		t.Fatalf("status: %s", doc.Agents[0].Status)
	}
	if doc.MaxDelegationDepth != 2 {
		t.Fatalf("max_delegation_depth: %d", doc.MaxDelegationDepth)
	}
	if doc.RevocationEndpoint == "" {
		t.Fatal("revocation_endpoint missing")
	}
}

// TestCrossLang_RustKey_GoSignVerify proves the Go SDK can load a
// Rust-generated PEM private key, issue a credential with it, and verify
// that credential against the same Rust-generated discovery document. This
// is the end-to-end interop guarantee for the issue/verify path.
func TestCrossLang_RustKey_GoSignVerify(t *testing.T) {
	privPEM := string(loadFixture(t, "example-2026-01.private.pem"))
	priv, err := crypto.LoadPrivateKey(privPEM)
	if err != nil {
		t.Fatalf("load Rust-generated private key: %v", err)
	}

	discData := loadFixture(t, "discovery.json")
	var disc types.DiscoveryDocument
	if err := json.Unmarshal(discData, &disc); err != nil {
		t.Fatal(err)
	}

	// Issue a fresh credential with the Rust-generated key.
	cred, err := credential.IssueCredential(
		priv,
		"example-2026-01",
		"example.com",
		"urn:agentpin:example.com:test-agent",
		"verifier.com",
		[]types.Capability{"read:data", "write:report"},
		nil, nil,
		3600,
	)
	if err != nil {
		t.Fatalf("issue: %v", err)
	}

	r := VerifyCredentialOffline(cred, &disc, nil, pinning.NewKeyPinStore(), "verifier.com", DefaultVerifierConfig())
	if !r.Valid {
		t.Fatalf("Go-issued credential against Rust-generated discovery failed: %+v", r)
	}
	if r.AgentID != "urn:agentpin:example.com:test-agent" {
		t.Fatalf("agent_id: %s", r.AgentID)
	}
}

// TestCrossLang_JWT_RustGenerated_GoVerify decodes a JWT generated by the
// Rust SDK against a Rust-generated public key file. This proves the JWT
// wire format (DER signature inside compact JWT) is identical across SDKs.
//
// The fixture credential lives inline because Rust-generated JWTs are short
// and embedding the bytes avoids tying CI to live Rust toolchain
// availability. The credential is signed with the testdata Rust key and
// uses iat/exp values that we override the verifier clock for.
func TestCrossLang_JWT_RustGenerated_GoDecodeAndSignatureVerify(t *testing.T) {
	pubPEM := string(loadFixture(t, "example-2026-01.public.pem"))
	pub, err := crypto.LoadPublicKey(pubPEM)
	if err != nil {
		t.Fatal(err)
	}

	// Sample Rust-generated JWT (alg=ES256, typ=agentpin-credential+jwt,
	// kid=example-2026-01) signed with the matching private key in
	// testdata/. The JWT's exp may be in the past; we are testing only the
	// header parsing + signature verification — not temporal validity.
	jwtStr := string(loadFixture(t, "credential.jwt"))

	// DecodeJWTUnverified MUST accept the Rust-generated header.
	header, payload, _, err := jwt.DecodeJWTUnverified(jwtStr)
	if err != nil {
		t.Fatalf("Go failed to decode Rust-generated JWT: %v", err)
	}
	if header.Alg != "ES256" || header.Typ != "agentpin-credential+jwt" {
		t.Fatalf("header drift: alg=%s typ=%s", header.Alg, header.Typ)
	}
	if header.Kid != "example-2026-01" {
		t.Fatalf("kid: %s", header.Kid)
	}
	if payload.Iss != "example.com" {
		t.Fatalf("iss: %s", payload.Iss)
	}
	if payload.AgentpinVersion != "0.1" {
		t.Fatalf("agentpin_version: %s", payload.AgentpinVersion)
	}

	// Signature MUST verify under the Rust-generated public key.
	if _, _, err := jwt.VerifyJWT(jwtStr, pub); err != nil {
		t.Fatalf("Go failed to verify Rust-generated JWT signature: %v", err)
	}
}
